#!/bin/bash

set -e -u

CMD=$(basename $0)
CMD_DIR=$(dirname $0)
source $CMD_DIR/lka-common

main()
{
	in_build_dir || exit 1

	find . -name '*.lka.*' -print |
		xargs --no-run-if-empty rm -f
}

main "$@"

